[build]
  command = "npx @netlify/plugin-nextjs@latest && npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://bgivemisrbkdtmbxojlu.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJnaXZlbWlzcmJrZHRtYnhvamx1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5Mjg0NDIsImV4cCI6MjA3MjUwNDQ0Mn0.mwYfMJQJQm-O4_-YJrZMJYrCgRUBw_M2BSB--m_qLG4"
  NODE_VERSION = "20"
  NETLIFY_NEXT_PLUGIN_SKIP = "false"

[[redirects]]
  from = "/_next/static/*"
  to = "/.netlify/functions/next_*"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next_index"
  status = 200


# Headers de seguran√ßa
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"